spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/ddd-db
    username: root
    password: mysqlpass
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

  # disable database initialisation with Spring JDBC, enabled by default
  flyway:
    url: jdbc:mysql://localhost:3307/ddd-db
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true
    baseline-on-migrate: true